### ISSUE TITLE
MUL and IMUL

### ISSUE THREAD

**Issue by Friedjof** [LuisRuisinger/era#3]
Multiplication by MUL would be assumed to be an unsigned operation and not a signed one as with IMUL. ([FILE](https://github.com/LuisRuisinger/era/blob/main/Script/Assembly%20/x86_32%20Assembly/x86_32%20Assembly%20-%20Unterkapitel/Besondere%20arithemtische%20Operationen.md#multiplikation))

**Comment by LuisRuisinger** [comment]
Yep i messed up there and swapped them. Should be fixed.
